- pipeline.id: "sample"
  path.config: "/usr/share/logstash/pipeline/sample.logstash.conf"
  pipeline.workers: 1
  pipeline.batch.size: 125
  config.reload.automatic: false
  config.debug: false
  config.support_escapes: false
  queue.type: "memory"
  queue.max_events: 0
  queue.drain: false
  dead_letter_queue.enable: false
